### ISSUE TITLE
build-plugin-component 依赖的 webpack 版本应该升级

### ISSUE THREAD

**Issue by yanbingbing** [ice-lab/build-scripts#118]
![image](https://user-images.githubusercontent.com/1620674/205798915-e12e5a7a-a59d-456d-a532-20d21128653b.png)
 build-scripts 和 build-plugin-react 等包依赖的 webpack 都是 5.x，就这个 build-plugin-component 依赖的还是 4.x
 
 导致在使用 pnpm 管理项目时，启动报错

**Comment by ClarkXia** [comment]
pnpm 的策略应该各自相关管自己的依赖，可以看下具体错误，另外  build-plugin-component 目前没有升级 webpack 5 的计划，新版 react 组件开发工具目前已经发布 https://github.com/ice-lab/icepkg

**Comment by yanbingbing** [comment]
@ClarkXia 新的  @ice/pkg 不支持 多 entry，配置项太少，用不起来，[笑哭]
