### ISSUE TITLE
ERR! Duplicate plugin/preset detected.

### ISSUE THREAD

**Issue by JackLian** [ice-lab/build-scripts#121]
复现步骤
1. https://github.com/alibaba/lowcode-engine 这个项目 develop 分支
```
tnpm install
npm run setup
npm run build
```
2. 看到报错
<img width="1138" alt="Screen Shot 2022-12-21 at 14 02 42" src="https://user-images.githubusercontent.com/2149847/208832982-5bcbf5b6-ee64-4b67-8667-7dc2cd26448f.png">

错误信息看的有点懵，麻烦帮忙看看如何解决下

**Comment by luhc228** [comment]
仓库锁了 @builder/babel-preset-ice 的版本，升级了 build-plugin-component 导致构建报错了
