### ISSUE TITLE
buidscript test 命令报错

### ISSUE THREAD

**Issue by JackLian** [ice-lab/build-scripts#122]
### 复现方式：
1. 仓库： https://code.alibaba-inc.com/liujuping.liujupin/build-plugin-component-bug/tree/master

2. 执行 
```bash
tnpm i
npm run test
```
3. 提示错误信息
<img width="970" alt="Screen Shot 2022-12-22 at 19 06 13" src="https://user-images.githubusercontent.com/2149847/209121196-f2efdcd0-83e2-4f8f-9fa7-771dc58c3b89.png">

4. 注释掉 line 11 ，错误会消失

### 期望结果
npm run test 可以正常 

### 注
 仓库是通过这个文档创建的
![image](https://user-images.githubusercontent.com/2149847/209121693-ac7a3169-119b-44b8-99db-33696dbf6923.png)

**Comment by luhc228** [comment]
目前先在项目根目录下添加 babel.config.js。(另外 jest 版本要在 ^26)
```js
module.exports = {
  plugins: [
    ['@babel/plugin-proposal-decorators', { version: 'legacy' }],
    [require.resolve('@babel/plugin-proposal-class-properties'), { loose: true }],
  ],
};
```
单测这块 build-plguin-components 能力不是很完善的，如果有更多的需求，可以使用 [icepkg](https://github.com/ice-lab/icepkg)

**Comment by JackLian** [comment]
感谢~
