### ISSUE TITLE
执行 npm init npm-template <pluginName> build-plugin-template 提示 taobao 镜像证书失效

### ISSUE THREAD

**Issue by public6326** [ice-lab/build-scripts#140]
在执行 npm init npm-template <pluginName> build-plugin-template 这条命令的时候 报错如图
![error](https://github.com/ice-lab/build-scripts/assets/8180305/ee73bff4-01f8-444f-9570-554358d5d7f1)

后检检查了本地无代理，npm 也切换多个镜像原。最后查询 'https://registry.npm.taobao.org/build-plugin-template',域名证书已经于 1 月 24 日到期。

是否有替代的命令可以生成模板？

**Comment by ClarkXia** [comment]
用 npm 官方镜像或者 npmmirror
