### ISSUE TITLE
userConfig 在不同插件中获取内容不统一

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/build-scripts#18]
通过 modifyUserConfig 修改后，最新的 userConfig 会在下一个执行插件中生效，而当前插件中通过 api.context.userConfig 没有发生变化

**Comment by crazybear** [comment]
如果 插件顺序 ["A", "B"];

如果在 B 中调用 modifyUserConfig 会造成context.userConfig 引用变更
插件 A 中 在后面的生命周期 或者 HOOK 中调用 api.context.userConfig 还是用的以前的引用

**Comment by ClarkXia** [comment]
已支持
