### ISSUE TITLE
希望支持vue工程的启动和构建

### ISSUE THREAD

**Issue by tyuqing** [ice-lab/build-scripts#21]
我们工程是用vue写的，正在使用飞冰开发自己的物料库，在开发页面级物料时发现build-scripts只支持react工程的调试和构建，希望build-scripts能支持vue工程的调试和构建

**Comment by ClarkXia** [comment]
build-scripts 本身不耦合具体工程配置，结合 https://github.com/alibaba/ice/tree/master/packages/plugin-react-app 插件的设计来支持 react 工程的调试和构建，可以参考针对 vue 链路进行实现

**Comment by tyuqing** [comment]
了解了 谢谢你。😊

**Comment by tyuqing** [comment]
我写了一个ice插件用来调试和构建vue物料，其中组件库是iview。有需要的话，供大家参考。
插件地址：https://github.com/codeless-js/codeless-cli/tree/master/packages/build-plugin-vue-iview
插件的使用可参考物料示例：https://github.com/codeless-js/vue-materials-iview/tree/master/pages/QueryTable
