### ISSUE TITLE
build命令保留旧文件夹

### ISSUE THREAD

**Issue by ChenKS12138** [ice-lab/build-scripts#22]
# 主要问题
使用`rax`构建微信小程序，使用`build/wechat-miniprogram`作为微信开发者工具的项目根目录，执行`rax-app build`命令后，文件夹`build/wechat-miniprogram`在构建过程中被删除并重新生成，旧文件夹的删除导致了微信开发者工具不能读取项目的`project.config.json`，不得不在微信开发者工具中重新打开项目。

我认为在执行build命令时，不删除文件夹`build/wechat-miniprogram`，而是仅清空`build/wechat-miniprogram`下的内容可能会更合理

# 复现步骤

## 环境
macOS 10.15.7
node v14.15.4
npm v7.4.3
rax-app v3.3.3
@alib/build-scripts v0.1.30

## 步骤

1. 执行 npm init rax rax-example创建项目
2. 下载依赖，使用`rax-app build`编译项目后，将`build/wechat-miniprogram`作为项目根目录使用微信开发者工具打开
3. 再次执行`rax-app build`，构建完成后，微信开发者工具不能正常读取项目内容
![image](https://user-images.githubusercontent.com/42082890/105869104-d77eaf80-6031-11eb-9356-ac1f02ada2d2.png)

# 尝试的解决方案
根据[rax文档的小程序配置](https://rax.js.org/docs/guide/miniapp-build-config)将项目根目录作为微信开发者工具的项目根目录，但是这需要在项目根目录创建`project.config.json`。个人认为`project.config.json`应该作为`rax`根据`build.config.js`构建的产物出现在`build/wechat-miniprogram`文件夹下更合理，同时，希望`project.config.json`中的`appid`是在构建过程中`build.config.js`读取环境变量生成的，因此这个方案不能满足我的要求。

**Comment by ChenKS12138** [comment]
Relevant #23

**Comment by ClarkXia** [comment]
已支持
