### ISSUE TITLE
支持自定义 webpack-dev-server 版本 ~

### ISSUE THREAD

**Issue by 94cstyles** [ice-lab/build-scripts#60]
RT

[webpack5 需要使用 webpack-dev-server@4 ](https://github.com/webpack/webpack-dev-server/issues/2758)

**Comment by ClarkXia** [comment]
已支持适配 https://github.com/ice-lab/build-scripts/pull/45 使用 build-scripts@1.1.0 版本

**Comment by imsobear** [comment]
build-scripts 版本

> 已支持适配 #45 使用 build-scripts@1.1.0 版本

好像没说怎么用。。
