### ISSUE TITLE
build-script打包时build目录未拷贝静态文件

### ISSUE THREAD

**Issue by zyy2008** [ice-lab/build-scripts#78]
build-script打包时build目录未拷贝静态文件
![image](https://user-images.githubusercontent.com/19901594/146138310-d1e07777-67f9-45c5-88ca-da8c2100f7e9.png)

**Comment by ClarkXia** [comment]
可以到对应的组件工程下提 issue https://github.com/ice-lab/iceworks-cli/issues ，组件工程中使用到的静态资源，建议放到 src/assets 下
