### ISSUE TITLE
demo 中的 md 代码问题

### ISSUE THREAD

**Issue by FrominXu** [ice-lab/build-scripts#86]
md 中的代码区不能正确显示在md文件中间位置，而是直接挂到了最末尾位置

**Comment by maoxiaoke** [comment]
和组件开发相关？

**Comment by FrominXu** [comment]
> 和组件开发相关？

是的，组件开发的md

**Comment by maoxiaoke** [comment]
@FrominXu https://github.com/ice-lab/iceworks-cli/tree/master/packages/build-plugin-component#demotemplate 可根据 demoTemplate 进行自定义

**Comment by FrominXu** [comment]
> @FrominXu https://github.com/ice-lab/iceworks-cli/tree/master/packages/build-plugin-component#demotemplate 可根据 demoTemplate 进行自定义

这个自定义具体怎么用的呢？我现在的问题是说代码渲染的位置会自动放到文档的最末尾，而不是md中相对应的位置，这个属于bug吧？

**Comment by maoxiaoke** [comment]
@FrominXu 具体可以在 https://github.com/ice-lab/iceworks-cli/issues 这个仓库开下 issue ，贴下图说明下
